### ISSUE TITLE
also support hide-behavior on new-form-item

### ISSUE THREAD

**Issue by guppylein** [DevExpress-Examples/DataGrid-How-to-hide-disable-Edit-Form-items-based-on-another-item-s-value#6]
Many thanks to this example (Angular), it helped me a lot. By the way, I missed the show/hide home address-behavior, when adding a new form-item.

To solve this issue, make the following changes in app.component.ts:

```
customizeItem = (item) => {
    if (item && item.itemType === "group" && item.caption === "Home Address") {
      let index = 0;
      if (this.rowKey != 0) {
        index = this.dataGrid.instance.getRowIndexByKey(this.rowKey) || 0;
      }      
      let isVisible = this.dataGrid.instance.cellValue(index, "AddressRequired");
      item.visible = isVisible;
    }
  }
```

let index == 0 by default and change index only, if rowKey is greater than 0.

in onInitNewRow init the rowKey with 0.
```
onInitNewRow(e) {
    this.rowKey = 0;

    e.data.AddressRequired = false;
    e.data.FirstName = "";
  }
```

Best regards,
Martin

**Comment by artem-kurchenko** [comment]
Hi,

Thank you for the report. We'll fix this issue
